'use strict';

const assert = require('assert');
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const ROOT = path.resolve(__dirname, '../..');
const PLUGIN_DIR = path.join(ROOT, 'plugins/doc-detective');
const README = path.join(PLUGIN_DIR, 'README.md');
const LICENSE = path.join(PLUGIN_DIR, 'LICENSE');
const PLUGIN_JSON = path.join(PLUGIN_DIR, '.claude-plugin/plugin.json');

describe('Plugin docs: generated README + LICENSE', function () {
  this.timeout(30000);

  before(function () {
    // generatePluginDocs() runs as part of the standard build.
    execFileSync('node', ['build.js', '--no-scripts'], { cwd: ROOT });
  });

  it('should generate plugins/doc-detective/README.md', function () {
    assert.ok(fs.existsSync(README), 'README.md must be generated by the build');
  });

  it('README should contain the plugin title and key sections', function () {
    const md = fs.readFileSync(README, 'utf8');
    assert.match(md, /^# doc-detective/m, 'README should start with the plugin title');
    assert.match(md, /## Commands/, 'README should list invocable commands');
    assert.match(md, /## License/, 'README should document the license');
  });

  it('README license should match the SPDX id in plugin.json', function () {
    const md = fs.readFileSync(README, 'utf8');
    const pj = JSON.parse(fs.readFileSync(PLUGIN_JSON, 'utf8'));
    assert.ok(md.includes(pj.license), 'README should reference plugin.json license');
  });

  it('README should omit install/harness-specific instructions', function () {
    const md = fs.readFileSync(README, 'utf8');
    assert.ok(
      !/\/plugin\s+(install|marketplace)/.test(md),
      'README must not contain plugin install instructions',
    );
  });

  it('agent summary should be truncated to its lead-in (no embedded examples)', function () {
    // Agent descriptions embed <example> blocks after escaped "\n" sequences;
    // the generated summary must stop before them. Guards the newline split.
    const md = fs.readFileSync(README, 'utf8');
    assert.ok(!md.includes('<example>'), 'agent summary should not include raw example blocks');
  });

  it('should copy the repo LICENSE into the plugin directory', function () {
    assert.ok(fs.existsSync(LICENSE), 'LICENSE must be copied into the plugin dir');
    const text = fs.readFileSync(LICENSE, 'utf8');
    assert.match(text, /GNU AFFERO GENERAL PUBLIC LICENSE/, 'LICENSE should be the AGPL v3 text');
  });
});
